- 👋 Hi, I’m @Sereenarrabi
- 👀 I’m interested to be Professional QA Engineer ...
- 🌱 I’m currently learning QA Automation ...
- 💞️ I’m looking to collaborate on Automation...
- 📫 How to reach me sereenar91@gmail.com...

<!---
Sereenarrabi/Sereenarrabi is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
